### ISSUE TITLE
chart.min.js:13 Uncaught SyntaxError: Cannot use import statement outside a module (at chart.min.js:13:1)

### ISSUE THREAD

**Issue by AlizerUncaged** [chartjs/chartjs-adapter-date-fns#70]
i get this error whenever i add
```
<script src="https://cdn.jsdelivr.net/npm/chart.js/dist/chart.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/chartjs-adapter-date-fns/dist/chartjs-adapter-date-fns.bundle.min.js"></script>
``` in my code

```
chart.min.js:13 Uncaught SyntaxError: Cannot use import statement outside a module (at chart.min.js:13:1)
```

**Comment by nagix** [comment]
Chart.js v4 doesn't include `chart.min.js` in `dist`, but jsDelivr returns the auto-generated minified version of `chart.js` which is the ESM file in v4, so this causes the error above. You can use the UMD file as follows:

```html
<script src="https://cdn.jsdelivr.net/npm/chart.js/dist/chart.umd.js"></script>
<script src="https://cdn.jsdelivr.net/npm/chartjs-adapter-date-fns/dist/chartjs-adapter-date-fns.bundle.min.js"></script>
```

Or, simply:
```html
<script src="https://cdn.jsdelivr.net/npm/chart.js@4"></script>
<script src="https://cdn.jsdelivr.net/npm/chartjs-adapter-date-fns@3"></script>
```
